INSERT INTO public.dataclassification (dataclassificationname) VALUES ('Restricted');
INSERT INTO public.dataclassification (dataclassificationname) VALUES ('Private');
INSERT INTO public.dataclassification (dataclassificationname) VALUES ('Public');

INSERT INTO public.deploymentenvironment (deploymentenvironmentname) VALUES ('Production');
INSERT INTO public.deploymentenvironment (deploymentenvironmentname) VALUES ('QA');
INSERT INTO public.deploymentenvironment (deploymentenvironmentname) VALUES ('Integrated Test');
INSERT INTO public.deploymentenvironment (deploymentenvironmentname) VALUES ('Performance');
INSERT INTO public.deploymentenvironment (deploymentenvironmentname) VALUES ('UAT');

INSERT INTO public.exposure (exposurename) VALUES('Internal');
INSERT INTO public.exposure (exposurename) VALUES('External');
INSERT INTO public.exposure (exposurename) VALUES('Customer Facing');

INSERT INTO public.language (languagename) VALUES('ABAP');
INSERT INTO public.language (languagename) VALUES('Ada');
INSERT INTO public.language (languagename) VALUES('Apex');
INSERT INTO public.language (languagename) VALUES('ASP');
INSERT INTO public.language (languagename) VALUES('AWK');
INSERT INTO public.language (languagename) VALUES('Bash');
INSERT INTO public.language (languagename) VALUES('BASIC');
INSERT INTO public.language (languagename) VALUES('C');
INSERT INTO public.language (languagename) VALUES('C++');
INSERT INTO public.language (languagename) VALUES('C#');
INSERT INTO public.language (languagename) VALUES('COBOL');
INSERT INTO public.language (languagename) VALUES('CoffeeScript');
INSERT INTO public.language (languagename) VALUES('ColdFusion');
INSERT INTO public.language (languagename) VALUES('Erlang');
INSERT INTO public.language (languagename) VALUES('F#');
INSERT INTO public.language (languagename) VALUES('Flex');
INSERT INTO public.language (languagename) VALUES('Fortran');
INSERT INTO public.language (languagename) VALUES('Fourth');
INSERT INTO public.language (languagename) VALUES('FoxPro');
INSERT INTO public.language (languagename) VALUES('Go');
INSERT INTO public.language (languagename) VALUES('Groovy');
INSERT INTO public.language (languagename) VALUES('Haskell');
INSERT INTO public.language (languagename) VALUES('HTML');
INSERT INTO public.language (languagename) VALUES('Informix');
INSERT INTO public.language (languagename) VALUES('J#');
INSERT INTO public.language (languagename) VALUES('Java');
INSERT INTO public.language (languagename) VALUES('JavaScript');
INSERT INTO public.language (languagename) VALUES('Jscript');
INSERT INTO public.language (languagename) VALUES('Jython');
INSERT INTO public.language (languagename) VALUES('Kotlin');
INSERT INTO public.language (languagename) VALUES('Korn shell');
INSERT INTO public.language (languagename) VALUES('Lasso');
INSERT INTO public.language (languagename) VALUES('LaTeX');
INSERT INTO public.language (languagename) VALUES('Lisp');
INSERT INTO public.language (languagename) VALUES('Objective-C');
INSERT INTO public.language (languagename) VALUES('Pascal');
INSERT INTO public.language (languagename) VALUES('Perl');
INSERT INTO public.language (languagename) VALUES('PHP');
INSERT INTO public.language (languagename) VALUES('PL/SQL');
INSERT INTO public.language (languagename) VALUES('PowerBuilder');
INSERT INTO public.language (languagename) VALUES('PowerShell');
INSERT INTO public.language (languagename) VALUES('Python');
INSERT INTO public.language (languagename) VALUES('R');
INSERT INTO public.language (languagename) VALUES('REXX');
INSERT INTO public.language (languagename) VALUES('Ruby');
INSERT INTO public.language (languagename) VALUES('Rust');
INSERT INTO public.language (languagename) VALUES('SAS');
INSERT INTO public.language (languagename) VALUES('SQL');
INSERT INTO public.language (languagename) VALUES('Swift');
INSERT INTO public.language (languagename) VALUES('Tcl');
INSERT INTO public.language (languagename) VALUES('T-SQL');
INSERT INTO public.language (languagename) VALUES('TypeScript');
INSERT INTO public.language (languagename) VALUES('Visual Basic');
INSERT INTO public.language (languagename) VALUES('Visual Basic .NET');
INSERT INTO public.language (languagename) VALUES('Visual FoxPro');
INSERT INTO public.language (languagename) VALUES('Visual J++');
INSERT INTO public.language (languagename) VALUES('Visual J#');
INSERT INTO public.language (languagename) VALUES('WebAssembly');
INSERT INTO public.language (languagename) VALUES('XML');
INSERT INTO public.language (languagename) VALUES('XPath');
INSERT INTO public.language (languagename) VALUES('XSLT');

INSERT INTO public.lifecyclestage (lifecyclestagename) VALUES('New');
INSERT INTO public.lifecyclestage (lifecyclestagename) VALUES('Active');
INSERT INTO public.lifecyclestage (lifecyclestagename) VALUES('Maintenance');
INSERT INTO public.lifecyclestage (lifecyclestagename) VALUES('Retired');

INSERT INTO public.risklevel (risklevelname) VALUES('High');
INSERT INTO public.risklevel (risklevelname) VALUES('Medium');
INSERT INTO public.risklevel (risklevelname) VALUES('Low');

INSERT INTO public.type (typename) VALUES('Library');
INSERT INTO public.type (typename) VALUES('Microservice');
INSERT INTO public.type (typename) VALUES('Monolith');
INSERT INTO public.type (typename) VALUES('Thin Client');
INSERT INTO public.type (typename) VALUES('User Interface');
INSERT INTO public.type (typename) VALUES('Web Site');